name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: jdk-17
    steps:
      - uses: actions/checkout@v4

      - name: Run backend tests
        working-directory: src/backend
        run: ./gradlew test

  frontend-tests:
    name: Frontend Tests
    runs-on: node-20
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: src/frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: src/frontend
        run: npx vitest run
