name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Install JDK 17
        run: |
          apt-get update -qq && apt-get install -y -qq openjdk-17-jdk > /dev/null 2>&1
          echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV

      - name: Run backend tests
        working-directory: src/backend
        run: |
          chmod +x gradlew
          ./gradlew test

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        working-directory: src/frontend
        run: npm ci

      - name: Run frontend tests
        working-directory: src/frontend
        run: npx vitest run
