name: Deploy Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Staging
    runs-on: deploy
    steps:
      - name: Checkout
        run: |
          apk add --no-cache git
          git clone --depth 1 $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git .

      - name: Build and deploy staging
        run: docker compose -p skiploom --profile staging up -d --build backend-staging frontend-staging

      - name: Verify staging deployment
        run: |
          echo "Waiting for backend-staging health..."
          timeout 60 sh -c 'until wget -q --spider http://backend-staging:8080/api/health 2>/dev/null; do sleep 2; done'
          echo "Backend healthy. Verifying frontend proxy..."
          wget -q --spider http://frontend-staging:80/api/health
          echo "Staging deployment verified."
